[Eth]
NetworkId = 
SyncMode = ""
LightPeers = 100
DatabaseCache = 230
EnablePreimageRecording = false

[Eth.Ethash]
CacheDir = ""
CachesInMem = 2
CachesOnDisk = 3
DatasetsInMem = 0
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01

[Node]
DataDir = ""
UseLightweightKDF = true
IPCPath = "geth.ipc"
HTTPHost = ""
HTTPPort = 
HTTPCors = []
HTTPVirtualHosts = ["localhost"]
HTTPModules = []
WSPort = 
WSModules = []

[Node.P2P]
MaxPeers = 25
